# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_pro:
            entity:
                class: AppBundle:Utilisateur
                property: email
                
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: my_pro
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            form_login: 
                check_path: /login
                login_path: /tchat
                
            logout:
                path: /logout
                target: /
            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    encoders:
        AppBundle\Entity\Utilisateur: plaintext
   
    access_denied_url: /
    
    access_control:
        - { path: ^/tchat, roles: ROLE_USER }

